### ISSUE TITLE
[3주차 24.05.12 ~ 24.05.18] 다이나믹 프로그래밍 (DP)

### ISSUE THREAD

**Issue by suyeoniii** [Algogosu/algorithm-solving#15]
- 백준 [퇴사](https://www.acmicpc.net/problem/14501)
- 백준 [평범한 배낭](https://www.acmicpc.net/problem/12865)
- LeetCode [746. Min Cost Climbing Stairs](https://leetcode.com/problems/min-cost-climbing-stairs/)
- LeetCode [22. Generate Parentheses](https://leetcode.com/problems/generate-parentheses/)
- 백준 [젠장](https://www.acmicpc.net/problem/1324)

**Comment by qus0in** [comment]
포도주 시식 https://www.acmicpc.net/problem/2156
점프 https://www.acmicpc.net/problem/1890
동물원 https://www.acmicpc.net/problem/1309
퇴사 https://www.acmicpc.net/problem/14501
평범한 배낭 https://www.acmicpc.net/problem/12865

**Comment by jeongyeon-park** [comment]
[746. Min Cost Climbing Stairs](https://leetcode.com/problems/min-cost-climbing-stairs/description/)
[1137. N-th Tribonacci Number](https://leetcode.com/problems/n-th-tribonacci-number/description/)

**Comment by gyulrangdev** [comment]
https://leetcode.com/problems/generate-parentheses/description/

**Comment by suyeoniii** [comment]
젠장 https://www.acmicpc.net/problem/1324
