### ISSUE TITLE
[2주차 24.05.05 ~ 24.05.11] 스택/큐/덱

### ISSUE THREAD

**Issue by suyeoniii** [Algogosu/algorithm-solving#5]
- Leet code [503. Next Greater Element II](https://leetcode.com/problems/next-greater-element-ii/)
- Leet Code [71. Simplify Path](https://leetcode.com/problems/simplify-path/)
- Leet code [원형큐 만들자](https://leetcode.com/problems/design-circular-queue/description)
- 백준 [라우터](https://www.acmicpc.net/problem/15828)
- 백준 [요세푸스 문제](https://www.acmicpc.net/problem/1158)

**Comment by gyulrangdev** [comment]
원형큐 만들자
https://leetcode.com/problems/design-circular-queue/description/

사람을 구해줘
https://leetcode.com/problems/boats-to-save-people/description/?envType=daily-question&envId=2024-05-04

**Comment by jeongyeon-park** [comment]
Leetcode [503. Next Greater Element II](https://leetcode.com/problems/next-greater-element-ii/)

백준 [요세푸스 문제](https://www.acmicpc.net/problem/1158) 

백준 [괄호](https://www.acmicpc.net/problem/9012)

**Comment by qus0in** [comment]
백준 [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
백준 [라우터](https://www.acmicpc.net/problem/15828)

**Comment by suyeoniii** [comment]
Leet Code [71. Simplify Path](https://leetcode.com/problems/simplify-path/)
Leet Code [387. First Unique Character in a String](https://leetcode.com/problems/first-unique-character-in-a-string/)
